### ISSUE TITLE
Make settings permanent

### ISSUE THREAD

**Issue by milesmcclane** [sadparadiseinhell/null#1]
Hi,

This is a great little start page, I have been using it adapted to my own needs, so thank you very much for sharing.

I would like to be able to 'hard code' the settings though, name, weather api and colour scheme etc, so as to avoid it reseting under certain conditions. Whilst I'm able to do basic things, such as add my own icons and links etc, my knowledge in such things is limited.

Do you have any advice on where to start?

Thanks,

MM

**Comment by sadparadiseinhell** [comment]
Hi,

To set your own name, change "Anon" in this line:
https://github.com/sadparadiseinhell/null/blob/8b28efba4766f75c09c6d6e3bc71a426df102ec0/js/greeting.js#L18

For the weather, you can replace the first "null" with your API key and the second with the city name, like this:
`getWeatherInfo('your API', 'city name');`
https://github.com/sadparadiseinhell/null/blob/8b28efba4766f75c09c6d6e3bc71a426df102ec0/js/weather.js#L18

To set your own color scheme change these values:
https://github.com/sadparadiseinhell/null/blob/8b28efba4766f75c09c6d6e3bc71a426df102ec0/css/style.css#L17-L30

**Comment by milesmcclane** [comment]
Wow, thanks for the concise and fast reply! Very kind of you. That worked well, except for the weather. That removed the ‘don’t forget your api’ warning, but didn’t add the weather. And it’s prevented any modifications using the sidebar. 

Any ideas?

**Comment by sadparadiseinhell** [comment]
Oh, sorry, it really doesn't work.
I changed the weather.js, now it should work. Just clone the repository again and try to do the same as before.

If you need Fahrenheit, change these lines, for example:
``if (!weatherLS) {
		temp = `${fahrenheit}\u00B0F`;
		radioFahrenheit.checked = true;
}``
https://github.com/sadparadiseinhell/null/blob/fc3d0532710d9457fa522d05bd2346070abe1993/js/weather.js#L105-L108

**Comment by milesmcclane** [comment]
Hi again, 

Thanks very much for looking in to this, and thanks for the changes, but I actually still cant get the weather to work! The same thing is happening as before.

I have cleared caches and stuff, tried using different broswers and private tabs, so it cant be related to that.

My apologies for my limited knowledge!

**Comment by sadparadiseinhell** [comment]
Hello. I checked, everything should work.
Make sure you have the latest version of the repository. For the weather to work the way you want, you only need to change it by editing the code, without changing the settings in the sidebar.

You need this line:
https://github.com/sadparadiseinhell/null/blob/fc3d0532710d9457fa522d05bd2346070abe1993/js/weather.js#L18
to look like this, for example: `getWeatherInfo('********************************', 'Tokyo');`

> '********************************' — your OpenWeatherMap API key.

If the error occurs again, open the dev tools in your browser and show the error in the console.

**Comment by milesmcclane** [comment]
![Screenshot 2021-03-09 at 13 03 08](https://user-images.githubusercontent.com/27552949/110467889-d7191000-80d7-11eb-9144-778e001130ac.png)
Here is the error line in the JS console

**Comment by sadparadiseinhell** [comment]
Please show how you changed the line of code.

**Comment by milesmcclane** [comment]
Do’t worry, I fixed it by generating a new api key, using that it now works. It’s weird because this original key worked when enetering it manually in the sidebar, that’s why I didnt think of that before.

Thank you so much for all of your help!

**Comment by sadparadiseinhell** [comment]
Oh, it's very good that everything works. 
You're welcome :)
