### ISSUE TITLE
Open search in the same tab

### ISSUE THREAD

**Issue by Kuuhhl** [sadparadiseinhell/null#2]
I would suggest opening the search in the same tab as the startpage.
Right now, each time I search, I have to manually close the startpage-tab.

**Comment by sadparadiseinhell** [comment]
If you want the search (and other links) to open on the same tab, you can comment out this line:

https://github.com/sadparadiseinhell/null/blob/fc3d0532710d9457fa522d05bd2346070abe1993/index.html#L9

**Comment by Kuuhhl** [comment]
Thanks!
